name: Deploy to Render
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Render
        uses: render-oss/deploy-render-action@v1
        with:
          renderToken: ${{ secrets.RENDER_TOKEN }}
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
